### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by ps222nq** [sebastiangus/1dv610-Coding-With-Requirements#6]
- Comments in controller could be made obsolete by naming of function and variable names:

//SET CURRENCT USERNAME IN VIEW, MAKES IT POSSIBLE TO KEEP SAME INPUT IN USERNAME FIELD AT NEXT RENDERING.
            $view ->setUsername();

could be 

$view->setUsernameForFormValue();

or something like that.

```
    //GET LOGIN CREDENTIALS FROM VIEW
    $this->loginView = $view;
    $username = $this->loginView->getRequestUserName();
    $password = $this->loginView->getRequestPassword();
```

This comment is already obsolete because of good naming

Also, the signature/timestamp comments at the top add no further value to the code and should be removed: 

/**
- Created by PhpStorm.
- User: sebastiangustavsson
- Date: 2016-09-22
- Time: 11:27
  */

**Comment by sebastiangus** [comment]
Comments removed, php-auto created comments also removed.
